### ISSUE TITLE
Add validate command

### ISSUE THREAD

**Issue by grayzu** [ms-henglu/armstrong#35]
I am sure this is part of the test command but having a separate command that will run terraform init and terraform plan so that users can validate that the generated configuration is what they expect before running test.

```bash
armstrong validate -path  {path to Terraform configuration files}
```

This command would output the terraform plan so that the user can ensure that the appropriate resources will be created.

**Comment by ms-henglu** [comment]
Hi @grayzu ,

I'm thinking we should rename the option `-path`, because now it will have 2 meanings which are confusing,
1. In `generate` command, it means path to a swagger 'Create' example
2. In other commands, it means path to Terraform configuration files

Maybe not necessary to provide an option specifying the working directory? Users can run `armstrong` after switching the working directory, and it's more straightforward.

WDYT?
